### ISSUE TITLE
Calibri does not work in my browser... ;(

### ISSUE THREAD

**Issue by cjduncana** [KayZak/-Sharing-the-code-I-wrote#1]
Calibri did not render in my browser, so instead it decided to render the text in Times New Roman. To prevent this from happening, you can do any of the following:
1. **Use a [Web Safe Font](http://www.w3schools.com/cssref/css_websafe_fonts.asp).** All browsers come with them.
2. **In the [`font-family`](http://www.w3schools.com/cssref/pr_font_font-family.asp), list more than one font.** In the case that your first-choice font fails, you can decide the font that functions as a fallback.
3. **Define the font as a [`@font-face`](http://www.w3schools.com/css/css3_fonts.asp).** If you have the font file, you can add it to your project with this method.
4. **Import it from a service like [Google Fonts](https://www.google.com/fonts).** You will not have to worry about the hosting of the font file. Let others worry about that.

**Comment by KayZak** [comment]
kk
