### ISSUE TITLE
ID selectors in the CSS: a no-no

### ISSUE THREAD

**Issue by cjduncana** [KayZak/-Sharing-the-code-I-wrote#2]
CSS conventions moved on this issue. Though in the past, it was recommended to use IDs as a CSS selector, now we recommend not to do this.

For more reasons why, you can visit [this article](http://oli.jp/2011/ids/) to learn about this convention.

**Comment by KayZak** [comment]
Cool, I'll read up on this. Will this article show me what to do to achieve the same thing?

**Comment by cjduncana** [comment]
Yes, or I can tell you. In the CSS,  replace the ID selector with an equivalent class selector. In the HTML, add a class attribute to the elements that has the ID selector. Fill the class attribute with the selector use used in the CSS.

Do note that you do not have to remove the ID attribute from the element. It is still useful in case you want to anchor or to use in JavaScript.

**Comment by KayZak** [comment]
Can you easily make an ID selector a Class selector? I found this:

<style>
    #main{
        background: #000;
        border: 1px solid #AAAAAA;
        padding: 10px;
        color: #fff;
        width: 100px;
    }
</style>

<div id="main">
    Welcome
</div>

and this:

<style>
    .main{
        background: #000;
        border: 1px solid #AAAAAA;
        padding: 10px;
        color: #fff;
        width: 100px;
    }
</style>

<div class="main">
    Welcome
</div>

IT looks like all you need to do is use a . instead of a #. Is that correct?

**Comment by KayZak** [comment]
http://stackoverflow.com/questions/12889362/difference-between-id-and-class-in-css-and-when-to-use-it

**Comment by cjduncana** [comment]
Yep, it is that easy. You just have to make sure that in your HTML file, that element has a class attribute.

**Comment by KayZak** [comment]
cool, will do
