### ISSUE TITLE
Do you want a responsive website?

### ISSUE THREAD

**Issue by cjduncana** [KayZak/-Sharing-the-code-I-wrote#5]
First of all, responsive web design approaches the world we live in where there are browsers for so many devices by making sure that the website we design work beautifully in all of them.

![Your Mobile Site in the Present](https://cloud.githubusercontent.com/assets/1977082/14407043/6d8ca414-fe80-11e5-9d2a-ae95c7011925.png)

If you want, we can work together to convert this site into a responsive one. In the process, you will have a better grasp of what can be done with HTML and CSS.

What do you think?

**Comment by KayZak** [comment]
Sounds good! I'm at my family's house and probably wont be able to take a deep look into this tonight. I'll get up early and make changes tomorrow.

**Comment by cjduncana** [comment]
Have in mind that the whole point of this kind of communication is that it is asynchronous. There is no expectation of an immediate response, as in Messenger.
