### ISSUE TITLE
From Internal Style Sheet and Inline Style to External Style Sheet

### ISSUE THREAD

**Issue by cjduncana** [KayZak/-Sharing-the-code-I-wrote#7]
One of the great things of CSS is that you write it once and you can apply it to every single page of the web site. To take advantage of this ability, we can cut the internal style sheet from the html file and paste it to an empty CSS file. It can be named `styles.css` or something similar. For more on this, you can read [this article](http://www.w3schools.com/css/css_howto.asp).

The other thing this helps with is what developers call `separation of concerns`. For example, right now the same document, your html file, is taking care of both the structure and style of the web page. Once those concerns are separated into separate files, when you want to modify something, instead of looking at one huge page where all the code is located, you look for the file that is responsible for that concern and modify it.

**Comment by KayZak** [comment]
Cool, I figured it out.
