### ISSUE TITLE
Over-Qualifying Elements

### ISSUE THREAD

**Issue by cjduncana** [KayZak/-Sharing-the-code-I-wrote#8]
In the following example, the rule is to find all of the elements of class `ex` that are also paragraphs:

```
p.ex {
    margin-top: 12px;
    margin-bottom: 12px;
    margin-right: 600px;
    margin-left: 150px;
}
```

This is an example of over-qualification. The only elements that have the `ex` class are paragraphs. You can replace the code with the following to achieve the same with less code:

```
.ex {
    margin-top: 12px;
    margin-bottom: 12px;
    margin-right: 600px;
    margin-left: 150px;
}
```

**Comment by KayZak** [comment]
Cool, gotcha
